export const SERVER_ERROR_CODE = 5000;

// HTTP ERROR CODES
export const BAD_REQUEST_ERROR_CODE = 400;

// EXCEPTION ERROR CODES
export const MALFORMED_REQUEST_ERROR_CODE = 1000;
export const UNAUTHORIZED_REQUEST_ERROR_CODE = 401;
export const QUERY_ERROR_CODE = 1001;
export const AUTH_ERROR_CODE = 1002;
export const INVALID_FUNCTION_OPTION_ERROR_CODE = 1003;
export const VALIDATION_ERROR_CODE = 1004;
export const UNKNOWN_ERROR_CODE = 1005;
export const UNAUTHORIZED_ERROR_CODE = 1006;
export const MISSING_REQUIRED_PARAMETER_ERROR = 1007;
export const USER_NOT_FOUND_ERROR_CODE = 1008;
export const INVALID_CREDENTIAL_ERROR_CODE = 1009;
export const INVALID_TOKEN_ERROR_CODE = 1010;
export const INVALID_CLIENT_ERROR_CODE = 1011;
export const RESOURCE_NOT_FOUND_ERROR_CODE = 1012;
export const DUPLICATE_ERROR_CODE = 1013;
