export enum PathsEnum {
  root = '/',
  defaultDashboard = '/admin/dashboard/default/',
  analyticsDashboard = '/admin/dashboard/analytics/',
  user = '/admin/users/',
  users = '/admin/users/list/',
  customers = '/admin/users/customers/',
  createUser = '/admin/users/create-user/',
  updateUser = '/admin/users/update-user/',
  permissions = '/admin/permissions/list/',
  permissionsTypes = '/admin/permissions/types/',
  createPermission = '/admin/permissions/crate-permission/',
  updatePermission = '/admin/permissions/update-permission/',
  permissionsRoles = '/admin/permissions/roles/',
  createPermissionRole = '/admin/permissions/create-role/',
  updatePermissionRole = '/admin/permissions/update-role/',
  createPermissionType = '/admin/permissions/create-permission-type/',
  updatePermissionType = '/admin/permissions/update-permission-type/',

  servicesList = '/admin/services/list/',
  service = '/admin/services/',
  departmentsList = '/admin/services/departments/list/',
  department = '/admin/services/departments/',
}
